### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by carlosroman**

### CODE REVIEW

**Comment by kovacshuni** [comment]
Are you sure do you want to send multiple concepts' publishing message with the same transaction id? The transaction id would serve no purpose, it won't differentiate more than the uuid would.

**Comment by carlosroman** [comment]
@kovacshuni yeah we want the same transaction ID as this is all one technically transaction. This republish is all one event and has one source that generates the data. This way we can follow a concepts ingestion all the way from the `concept-publisher` to a reader/writer. If everything has the same TID we can then verify in Splunk that the r/w got everything that was published by that event. Think of it as a way to group all the events in one bucket, making things easier to track and support.

**Comment by nwrigh** [comment]
I initially had exactly the same reaction but Carlos pointed out the benefits from a tracking point of view and i was sold

**Comment by kovacshuni** [comment]
I see your point. I would like to ask one more opinion from @sjwells

**Comment by sjwells** [comment]
This makes sense to me - the transaction we are interested in is the publish.

**Comment by kovacshuni** [comment]
cool, i'm fine with this, then :) +1

**Pull request merged**
